edition = "2021"
version = "Two"
unstable_features = true

max_width = 120
use_small_heuristics = "Max"

#indent_style = "Visual"
imports_indent = "Visual"
imports_layout = "Horizontal"
imports_granularity = "Crate"
group_imports = "One"
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

fn_args_layout = "Compressed"
#fn_single_line = true
where_single_line = true
hex_literal_case = "Lower"
match_arm_blocks = false
overflow_delimited_expr = true
reorder_impl_items = true
